---
openapi: 3.0.3
info:
  title: BingleShop RESTful API
  description: OpenAPI for Getting and Adding Items Data
  version: ''
servers:
  - url: http://localhost:3002/api/
paths:
  "/v2/items": 
     $ref: './path/get-and-create-item.yaml'