---
openapi: 3.0.3
info:
  title: BingleShop RESTful API
  description: ''
  version: ''
servers:
  - url: http://localhost:3002/api/
paths:
  /api/users/register:
    $ref: './path/users/register.yaml'
  /api/users/login:
    $ref: './path/users/login.yaml'
  /api/users/my-profile:
    $ref: './path/users/get-user.yaml'
  /api/users/update:
    $ref: './path/users/update-user.yaml'
  /v2/orders:
    $ref: './path/orders/create-get-order.yaml'
  /v2/orders/{orderId}:
    $ref: './path/orders/update-order.yaml'
  /v2/items/{itemId}:
    $ref: './path/items/update-delete-item.yaml'
  /api/items:
    $ref: './path/items/get-and-create-item.yaml'

