---
openapi: 3.0.3
info:
  title: BingleShop RESTful API
  description: OpenAPI for Getting and Adding Items Data
  version: ''
servers:
- url: http://localhost:3002/api/
paths:
  "/v2/items":
    get:
      tags:
      - BingleShop Items Data
      summary: Get All Items Data
      description: Get all active items data by default
      responses:
        '200':
          description: Success get all items data
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/BingleShop_itemsData"
              examples:
                javascript::
                  description: Getting all items data
                  value:
                  - item_id: '1'
                    item_name: NutriJon
                    stock: 30
                    price: 30000
                    description: Dessert
                  - item_id: '2'
                    item_name: Mamak Melon
                    stock: 15
                    price: 20000
                    description: Dish Soap
        '400':
          description: Invalid input
      security:
        - BingleShopAuth:
          - write:users
          - read:users
    post:
      tags:
      - BingleShop Items Data
      summary: Create a new item data
      description: Try to create new item data to database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Create_new_ItemData"
            examples:
              javascript:
                description: Example create new item data
                value:
                  item_name: Black Bean
                  stock: 20
                  price: 30000
                  description: Margarin
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Create_new_ItemData"
              examples:
                javascript:
                  description: Successfully created new item data
                  value:
                    Success: 1
                    message: ITEM_CREATED
                    data:
                      item_name: Black Bean
                      stock: 20
                      price: 30000
                      description: Margarin          
        '400':
          description: Invalid input
        '422':
          description: Validation exception
      security:
      - BingleShopAuth:
        - write:users
        - read:users
components:
  securitySchemes:
    BingleShopAuth:
      description: authentication for BingleShop RESTful API
      type: apiKey
      in: header
      name: X-API-apiKey
  schemas:
    BingleShop_itemsData:
     type: object
     properties:
       id:
         type: integer
       item_name:
         type: string
         required: 
         - 'true'
       stock:
         type: integer
         required: 
         - 'true'
       price:
         type: integer
         required: 
         - 'true'
       picture:
         type: string
         required: 
         - 'true'
       description:
         type: string
         required: 
         - 'true'
    Create_new_ItemData:
      type: object
      properties:
        item_name:
         type: string
         required: 
         - 'true'
        stock:
         type: integer
         required: 
         - 'true'
        price:
         type: integer
         required: 
         - 'true'
        picture:
         type: string
         required: 
         - 'true'
        description:
         type: string
         required: 
         - 'true'
  
