# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main " ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout current branch
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install nodejs packages
      run: npm install --silent

    - name: Run sequelize module to create database and migration
      run: |
        npx sequelize db:create
        npx sequelize db:migrate
      env:
        NODE_ENV: test
        POSTGRES_USER: ${{ vars.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
        POSTGRES_DB: ${{ vars.POSTGRES_DB }}

    - name: Run integration test
      run: npm run integration
      env:
        POSTGRES_USER: ${{ vars.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
        POSTGRES_DB: ${{ vars.POSTGRES_DB }}
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
  
  deploy-vercel:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  # this is the deployment sample for VPS or compute engine instance
  deploy-to-vps:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      # - name: Use current build artifact
      #   uses: actions/download-artifact@v3.1.3
      #   with:
      #     name: binar-artifact

      - name: Checkout current branch
        uses: actions/checkout@v2

      - name: Prepare .env file
        run: |
          touch .env #bikin file .env ke current directory
          echo "DB_USERNAME_PROD=${{ secrets.DB_USERNAME_PROD }}" >> .env #menuliskan env beserta isinya, lalu di append ke file .env
          echo "DB_PASS_PROD=${{ secrets.DB_PASS_PROD }}" >> .env
          echo "DB_NAME_PROD=${{ secrets.DB_NAME_PROD }}" >> .env
          echo "DB_HOST_PROD=${{ secrets.DB_HOST_PROD }}" >> .env
          echo "DB_PORT_PROD=${{ secrets.DB_PORT_PROD }}" >> .env
          echo "DB_DIALECT_PROD=${{ secrets.DB_DIALECT_PROD }}" >> .env
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET }}" >> .env
          echo "CLOUDINARY_URL=${{ secrets.CLOUDINARY_URL }}" >> .env
          echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> .env
          echo "EMAIL_PASS=${{ secrets.EMAIL_PASS }}" >> .env
          echo "HOST_PROD==${{ secrets.HOST_PROD }}" >> .env

      - name: Upload to VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: '.'
          target: ./bingleshop-team2/BingleShop-Team2

      - name: restart pm2 services
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            npm install --silent
            pm2 restart binar-bingle-shop
